export enum GoogleMapsRegion {
    US = 'US',
    RU = 'RU',
    TR = 'TR',
    DE = 'DE',
    FR = 'FR',
    ES = 'ES',
    IT = 'IT',
    JP = 'JP',
    KR = 'KR',
    CN = 'CN',
    TW = 'TW',
    BR = 'BR',
    GB = 'GB',
    CA = 'CA',
    AU = 'AU',
    IN = 'IN',
    PL = 'PL',
    NL = 'NL',
    SE = 'SE',
    NO = 'NO',
    FI = 'FI',
    DK = 'DK',
    CZ = 'CZ',
    UA = 'UA',
    RO = 'RO',
    HU = 'HU'
  }